Clone repo to pull Vim dotfiles
- major fix for Vim installer, MUST clone repo before copying .vimrc

Resolves: #37

Signed-off-by: Daniel Andrei Minca <mandrei17@gmail.com>

diff --git a/init b/init
--- a/init
+++ b/init
@@ -201,6 +201,9 @@ installVim() {
   git clone https://github.com/dyng/ctrlsf.vim.git $VIM_PATH/bundle/ctrlsf.vim
 
   # move dotfiles in $HOME
+  if [[ ! -d $REPO_PATH ]]; then
+    git clone https://github.com/dminca/dotfiles.git $DOWNLOADS_DIR/dotfiles
+  fi
   cp -fv $DOTFILES_PATH/.vimrc $HOME
   cp -Rv $REPO_PATH/snippets/* $HOME/.vim/snippets/
 }
@@ -208,6 +211,10 @@ installVim() {
 installDotfiles() {
   breakline "Copying and configuring dotfiles"
 
+  if [ -e "$HOME/.vimrc" -a -e "$HOME/.bashrc" -a -e "$HOME/.tmux.conf" ]; then
+    printf "$light_red" "[ERROR] Dotfiles have already been copied. Exiting..."
+    exit 1
+  fi
   git clone https://github.com/dminca/dotfiles.git $DOWNLOADS_DIR/dotfiles
 
   cp -fv $DOTFILES_PATH/.taskrc \
@@ -215,8 +222,6 @@ installDotfiles() {
      $DOTFILES_PATH/.tmux.conf \
      $DOTFILES_PATH/.bash_aliases \
      $DOTFILES_PATH/.gemrc $HOME/
-
-
 }
 
 installTask() {
