Major refactor: order functions alfabetically
Signed-off-by: Minca Daniel Andrei <mandrei17@gmail.com>

diff --git a/init b/init
--- a/init
+++ b/init
@@ -29,7 +29,8 @@ dark_gray='\e[1;100m%s\e[0m\n'
 
 # -- endcolors --
 
-breakline() {
+breakline ()
+{
   TXT="----| ${1} |----"
   TXT_LENGTH=$(expr length "${TXT}")
   NL=$'\n'
@@ -37,45 +38,8 @@ breakline() {
 }
 
 # ---- end helper func. -------------------
-
-installWireshark ()
+installAdobe ()
 {
-  breakline "Installing Wireshark"
-
-  which wireshark > /dev/null 2>&1
-  if [[ $? -eq 0 ]]; then
-    printf "$light_red" "[ERROR] Wireshark already installed. Exiting..."
-    exit 1
-  fi
-  printf "$light_green" "[OK] Installing..."
-  sudo apt-get install -y wireshark
-  sudo groupadd wireshark
-  sudo usermod -a -G wireshark $USER
-  sudo chgrp wireshark /usr/bin/dumpcap
-  sudo chmod 750 /usr/bin/dumpcap
-  sudo setcap cap_net_raw,cap_net_admin=eip /usr/bin/dumpcap
-  sudo getcap /usr/bin/dumpcap
-}
-
-#-------------------------------------------------------------------------
-#  Cleanup memory by removing all unused Linux Kernel headers, images and
-#  modules
-#-------------------------------------------------------------------------
-cleanup_memory ()
-{
-  dpkg -l 'linux-*' > /dev/null 2>&1
-  if [[ $? -ne 0 ]]; then
-    printf "$light_red" "No linux headers...exiting"
-    exit 1
-  fi
-  dpkg -l 'linux-*' |\
-  sed '/^ii/!d;/'"$(uname -r |\
-  sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' |\
-  xargs sudo apt-get -y purge
-}
-
-
-installAdobe() {
   # if the file wasn't downloaded
   if [[ ! -e "$DOWNLOADS_DIR/$ADOBE_PACKAGE" ]]; then
     # grab the .deb
@@ -97,8 +61,133 @@ installAdobe() {
   exit 1
 }
 
+installAnsible ()
+{
+  breakline "Installing Ansible"
+
+  which ansible > /dev/null 2>&1
+  if [[ $? -eq 0 ]]; then
+    printf "$light_red" "[ERROR] Ansible already installed. Exiting..."
+    exit 1
+  fi
+  sudo apt-add-repository ppa:ansible/ansible --yes
+  sudo apt-get update && sudo apt-get install -y ansible
+}
+
+installChrome ()
+{
+  breakline "Installing Google Chrome"
+
+  apt-cache show google-chrome-stable > /dev/null 2>&1
+  if [[ "$?" -eq 0 ]]; then
+    printf "$light_red" "[ERROR] Chrome already installed. Exiting..."
+    exit 1
+  fi
+  # Install dependencies
+  sudo apt-get -y install \
+    libxss1 \
+    libappindicator1 \
+    libindicator7
+
+  # Fetch the Chrome acrhive
+  sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
+
+  # Install Chrome
+  sudo dpkg -i google-chrome*.deb
+
+  # Cleanup
+  sudo rm -f google-chrome-stable_current_amd64.deb
+}
+
+# setup docker
+installDocker ()
+{
+
+  breakline "Installing Docker"
+    
+  set -xv
+  which docker > /dev/null 2>&1
+  if [[ $? -eq 0 ]]; then
+    printf "$light_red" "[ERROR] Docker already installed. Exiting..."
+    exit 1
+  fi
+  Install  docker
+  curl -sSL https://get.docker.com/ | sh
+  sudo usermod -aG docker $USER
+
+
+  # Install docker-compose
+  sudo chown -R $(whoami) /usr/local/bin
+  curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
+  chmod +x /usr/local/bin/docker-compose
+}
+
+installDotfiles ()
+{
+  breakline "Copying and configuring dotfiles"
+
+  if [ -e "$HOME/.vimrc" -a -e "$HOME/.bashrc" -a -e "$HOME/.tmux.conf" ]; then
+    printf "$light_red" "[ERROR] Dotfiles have already been copied. Exiting..."
+    exit 1
+  fi
+  git clone https://github.com/dminca/dotfiles.git $DOWNLOADS_DIR/dotfiles
+
+  cp -fv $DOTFILES_PATH/.taskrc \
+     $DOTFILES_PATH/.bashrc \
+     $DOTFILES_PATH/.tmux.conf \
+     $DOTFILES_PATH/.bash_aliases \
+     $DOTFILES_PATH/.gemrc $HOME/
+}
+
+installDropbox ()
+{
+  breakline "Installing Dropbox"
+
+  apt-cache show dropbox > /dev/null 2>&1
+  if [[ "$?" -eq 0 ]]; then
+    printf "$light_red" "[ERROR] Dropbox already installed. Exiting..."
+    exit 1
+  fi
+  wget -P $DOWNLOADS_DIR https://linux.dropbox.com/packages/ubuntu/$DROPBOX_VERSION
+
+  sudo dpkg -i $DOWNLOADS_DIR/$DROPBOX_VERSION
+}
+
+installFont ()
+{
+  breakline "Pulling the Hack font"
+
+  if [[ -e "$HOME/.fonts/truetype/Hack-Regular.ttf" ]]; then
+    printf "$light_red" "[ERROR] Hack font already installed. Exiting..."
+    exit 1
+  fi
+  mkdir -p $HOME/.fonts/truetype
+  wget -P $HOME/.fonts/truetype https://github.com/chrissimpkins/Hack/releases/download/v2.018/Hack-v2_018-ttf.zip
+  unzip $HOME/.fonts/truetype/Hack-v2_018-ttf.zip -d $HOME/.fonts/truetype/
+
+  # post-install cleanup
+  rm -rfv $HOME/.fonts/truetype/Hack-v2_018-ttf.zip
+}
+
+installNode ()
+{
+  breakline "Installing Node (latest)"
+
+  node --version > /dev/null 2>&1
+  if [[ $? -eq 0 ]]; then
+    printf "$light_red" "[ERROR] NodeJS already installed. Exiting..."
+    exit 1
+  fi
+  wget -P $DOWNLOADS_DIR https://nodejs.org/dist/${NODE_VERSION[0]}/${NODE_VERSION[1]}.tar.gz
+
+  tar xvf $DOWNLOADS_DIR/${NODE_VERSION[1]}.tar.gz -C $DOWNLOADS_DIR
+
+  sudo cp -vr $DOWNLOADS_DIR/${NODE_VERSION[1]}/* /usr/local/
+}
+
 # Install libraries
-installPkgs() {
+installPkgs ()
+{
   sudo add-apt-repository ppa:git-core/ppa --yes
 
   sudo apt-get update
@@ -139,41 +228,62 @@ installPkgs() {
   sudo pip install --upgrade virtualenv
 }
 
-installAnsible() {
-  breakline "Installing Ansible"
+installSublime ()
+{
+  breakline "Installing Sublime Text 3 build 3065"
 
-  which ansible > /dev/null 2>&1
-  if [[ $? -eq 0 ]]; then
-    printf "$light_red" "[ERROR] Ansible already installed. Exiting..."
+  subl --version > /dev/null 2>&1
+  if [[ "$?" -eq 0 ]]; then
+    printf "$light_red" "[ERROR] Sublime already installed. Exiting..."
     exit 1
   fi
-  sudo apt-add-repository ppa:ansible/ansible --yes
-  sudo apt-get update && sudo apt-get install -y ansible
+  wget -P $DOWNLOADS_DIR http://c758482.r82.cf2.rackcdn.com/sublime-text_build-3065_amd64.deb
+
+  sudo dpkg -i $DOWNLOADS_DIR/sublime-text_build-3065_amd64.deb
+
+  wget -P $DOWNLOADS_DIR -O $DOWNLOADS_DIR/sublime_text http://cl.ly/1z0S25150Y0I/sublime_text%20crack%20linux%2064%20build%203065
+
+  chmod u+x $DOWNLOADS_DIR/sublime_text
+
+  sudo mv -v $DOWNLOADS_DIR/sublime_text /opt/sublime_text/
 }
 
-# setup docker
-installDocker() {
+installTask ()
+{
+  breakline "Installing tasksh by taskwarrior"
 
-  breakline "Installing Docker"
-    
-  set -xv
-  which docker > /dev/null 2>&1
-  if [[ $? -eq 0 ]]; then
-    printf "$light_red" "[ERROR] Docker already installed. Exiting..."
+  which tasksh > /dev/null 2>&1
+  if [[ "$?" -eq 0 ]]; then
+    printf "$light_red" "[ERROR] TaskSH has already been installed. Exiting..."
     exit 1
   fi
-  Install  docker
-  curl -sSL https://get.docker.com/ | sh
-  sudo usermod -aG docker $USER
+  wget http://taskwarrior.org/download/tasksh-latest.tar.gz --directory-prefix=$DOWNLOADS_DIR
 
+  cd $DOWNLOADS_DIR
 
-  # Install docker-compose
-  sudo chown -R $(whoami) /usr/local/bin
-  curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
-  chmod +x /usr/local/bin/docker-compose
+  tar xvf tasksh-latest.tar.gz
+
+  cd tasksh-*
+
+  cmake --version 2>&1 > /dev/null
+  if [ "$?" -ne 0 ]; then
+    printf "$light_red" "[ERROR] Could not find cmake."
+    exit 1
+  fi
+
+  cmake -DCMAKE_BUILD_TYPE=release .
+
+  sleep 2
+
+  make
+
+  sudo make install
+
+  cd $HOME
 }
 
-installVim() {
+installVim ()
+{
   breakline "Configuring vim & pulling plugins"
 
   if [[ -d "$VIM_PATH" ]]; then
@@ -212,146 +322,27 @@ installVim() {
   cp -Rv $REPO_PATH/snippets/* $HOME/.vim/snippets/
 }
 
-installDotfiles() {
-  breakline "Copying and configuring dotfiles"
+installWireshark ()
+{
+  breakline "Installing Wireshark"
 
-  if [ -e "$HOME/.vimrc" -a -e "$HOME/.bashrc" -a -e "$HOME/.tmux.conf" ]; then
-    printf "$light_red" "[ERROR] Dotfiles have already been copied. Exiting..."
-    exit 1
-  fi
-  git clone https://github.com/dminca/dotfiles.git $DOWNLOADS_DIR/dotfiles
-
-  cp -fv $DOTFILES_PATH/.taskrc \
-     $DOTFILES_PATH/.bashrc \
-     $DOTFILES_PATH/.tmux.conf \
-     $DOTFILES_PATH/.bash_aliases \
-     $DOTFILES_PATH/.gemrc $HOME/
-}
-
-installTask() {
-  breakline "Installing tasksh by taskwarrior"
-
-  which tasksh > /dev/null 2>&1
-  if [[ "$?" -eq 0 ]]; then
-    printf "$light_red" "[ERROR] TaskSH has already been installed. Exiting..."
-    exit 1
-  fi
-  wget http://taskwarrior.org/download/tasksh-latest.tar.gz --directory-prefix=$DOWNLOADS_DIR
-
-  cd $DOWNLOADS_DIR
-
-  tar xvf tasksh-latest.tar.gz
-
-  cd tasksh-*
-
-  cmake --version 2>&1 > /dev/null
-  if [ "$?" -ne 0 ]; then
-    printf "$light_red" "[ERROR] Could not find cmake."
-    exit 1
-  fi
-
-  cmake -DCMAKE_BUILD_TYPE=release .
-
-  sleep 2
-
-  make
-
-  sudo make install
-
-  cd $HOME
-}
-
-installChrome() {
-
-  breakline "Installing Google Chrome"
-
-  apt-cache show google-chrome-stable > /dev/null 2>&1
-  if [[ "$?" -eq 0 ]]; then
-    printf "$light_red" "[ERROR] Chrome already installed. Exiting..."
-    exit 1
-  fi
-  # Install dependencies
-  sudo apt-get -y install \
-    libxss1 \
-    libappindicator1 \
-    libindicator7
-
-  # Fetch the Chrome acrhive
-  sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
-
-  # Install Chrome
-  sudo dpkg -i google-chrome*.deb
-
-  # Cleanup
-  sudo rm -f google-chrome-stable_current_amd64.deb
-
-}
-
-installFont() {
-  breakline "Pulling the Hack font"
-
-  if [[ -e "$HOME/.fonts/truetype/Hack-Regular.ttf" ]]; then
-    printf "$light_red" "[ERROR] Hack font already installed. Exiting..."
-    exit 1
-  fi
-  mkdir -p $HOME/.fonts/truetype
-  wget -P $HOME/.fonts/truetype https://github.com/chrissimpkins/Hack/releases/download/v2.018/Hack-v2_018-ttf.zip
-  unzip $HOME/.fonts/truetype/Hack-v2_018-ttf.zip -d $HOME/.fonts/truetype/
-
-  # post-install cleanup
-  rm -rfv $HOME/.fonts/truetype/Hack-v2_018-ttf.zip
-}
-
-installDropbox() {
-  breakline "Installing Dropbox"
-
-  apt-cache show dropbox > /dev/null 2>&1
-  if [[ "$?" -eq 0 ]]; then
-    printf "$light_red" "[ERROR] Dropbox already installed. Exiting..."
-    exit 1
-  fi
-  wget -P $DOWNLOADS_DIR https://linux.dropbox.com/packages/ubuntu/$DROPBOX_VERSION
-
-  sudo dpkg -i $DOWNLOADS_DIR/$DROPBOX_VERSION
-
-}
-
-installSublime() {
-  breakline "Installing Sublime Text 3 build 3065"
-
-  subl --version > /dev/null 2>&1
-  if [[ "$?" -eq 0 ]]; then
-    printf "$light_red" "[ERROR] Sublime already installed. Exiting..."
-    exit 1
-  fi
-  wget -P $DOWNLOADS_DIR http://c758482.r82.cf2.rackcdn.com/sublime-text_build-3065_amd64.deb
-
-  sudo dpkg -i $DOWNLOADS_DIR/sublime-text_build-3065_amd64.deb
-
-  wget -P $DOWNLOADS_DIR -O $DOWNLOADS_DIR/sublime_text http://cl.ly/1z0S25150Y0I/sublime_text%20crack%20linux%2064%20build%203065
-
-  chmod u+x $DOWNLOADS_DIR/sublime_text
-
-  sudo mv -v $DOWNLOADS_DIR/sublime_text /opt/sublime_text/
-
-}
-
-installNode() {
-  breakline "Installing Node (latest)"
-
-  node --version > /dev/null 2>&1
+  which wireshark > /dev/null 2>&1
   if [[ $? -eq 0 ]]; then
-    printf "$light_red" "[ERROR] NodeJS already installed. Exiting..."
+    printf "$light_red" "[ERROR] Wireshark already installed. Exiting..."
     exit 1
   fi
-  wget -P $DOWNLOADS_DIR https://nodejs.org/dist/${NODE_VERSION[0]}/${NODE_VERSION[1]}.tar.gz
-
-  tar xvf $DOWNLOADS_DIR/${NODE_VERSION[1]}.tar.gz -C $DOWNLOADS_DIR
-
-  sudo cp -vr $DOWNLOADS_DIR/${NODE_VERSION[1]}/* /usr/local/
+  printf "$light_green" "[OK] Installing..."
+  sudo apt-get install -y wireshark
+  sudo groupadd wireshark
+  sudo usermod -a -G wireshark $USER
+  sudo chgrp wireshark /usr/bin/dumpcap
+  sudo chmod 750 /usr/bin/dumpcap
+  sudo setcap cap_net_raw,cap_net_admin=eip /usr/bin/dumpcap
+  sudo getcap /usr/bin/dumpcap
 }
 
-installZsh() {
+installZsh ()
+{
   breakline "Installing Zshell (zsh)"
 
   which zsh > /dev/null 2>&1
@@ -364,8 +355,36 @@ installZsh() {
   sh $HOME/Downloads/install.sh
 }
 
+#-------------------------------------------------------------------------
+#  Cleanup memory by removing all unused Linux Kernel headers, images and
+#  modules
+#-------------------------------------------------------------------------
+cleanup_memory ()
+{
+  dpkg -l 'linux-*' > /dev/null 2>&1
+  if [[ $? -ne 0 ]]; then
+    printf "$light_red" "No linux headers...exiting"
+    exit 1
+  fi
+  dpkg -l 'linux-*' |\
+  sed '/^ii/!d;/'"$(uname -r |\
+  sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' |\
+  xargs sudo apt-get -y purge
+}
+
+clearInstall ()
+{
+  breakline "Cleaning after installation"
+
+  rm -rfv $REPO_PATH \
+         $DOWNLOADS_DIR/tasksh-* \
+         $DOWNLOADS_DIR/$DROPBOX_VERSION \
+         $DOWNLOADS_DIR/node-v5.1.0-linux-x64*
+}
+
 # extra packages for design
-themePaper() {
+themePaper ()
+{
   breakline "Installing Paper theme and Icon pack"
 
   apt-cache show paper-gtk-theme > /dev/null 2>&1
@@ -380,7 +399,8 @@ themePaper() {
   sudo apt-get install -y paper-gtk-theme paper-icon-theme
 }
 
-themeNumix() {
+themeNumix ()
+{
   breakline "Installing Numix themne and Icon pack"
 
   apt-cache show numix-icon-theme > /dev/null 2>&1
@@ -395,17 +415,8 @@ themeNumix() {
   sudo apt-get install -y numix-icon-theme numix-icon-theme-circle
 }
 
-
-clearInstall() {
-  breakline "Cleaning after installation"
-
-  rm -rfv $REPO_PATH \
-         $DOWNLOADS_DIR/tasksh-* \
-         $DOWNLOADS_DIR/$DROPBOX_VERSION \
-         $DOWNLOADS_DIR/node-v5.1.0-linux-x64*
-}
-
-selectiveInstall() {
+selectiveInstall ()
+{
   whiptail --title "Package chooser" --checklist --separate-output \
     "What packages do you wish to install?" 20 78 15 \
     "bins" "Install binaries" off \
@@ -485,7 +496,6 @@ selectiveInstall() {
         ;;
     esac
   done < results
-
 }
 
 if [  "$#" -lt 1  ]
