Improve init and add transfer.sh support
- when installing 'tasksh' from TaskWarrior, installer would fail if
  'cmake' wasn't installed on some hosts,
    As a result, only install the TaskWarrior if cmake is present, else
    exit with code 1
- add support for transfer.sh to send files to the web from the CLI
  easily

source: https://transfer.sh

Signed-off-by: Minca Daniel Andrei <mandrei17@gmail.com>

diff --git a/init b/init
--- a/init
+++ b/init
@@ -170,6 +170,12 @@ installTask() {
 
   cd tasksh-*
 
+  cmake --version 2>&1 > /dev/null
+  if [ "$?" -ne 0 ]; then
+    printf "$light_red" "Could not find cmake."
+    return 1
+  fi
+
   cmake -DCMAKE_BUILD_TYPE=release .
 
   sleep 2
