Reorder functions & add vars file
- hold all variables in 'vars' file
- order functions alphabetically in the installer
- WIP on bats tests, if program is installed, skip test

Signed-off-by: Minca Daniel Andrei <mandrei17@gmail.com>

diff --git a/init b/init
--- a/init
+++ b/init
@@ -3,32 +3,7 @@
 # Copyright (C) 2015 Minca Daniel Andrei - All Rights Reserved
 # Permission to copy and modify is granted under the GPL V2 license
 set -euo pipefail
-
-VIM_PATH="$HOME/.vim"
-DOWNLOADS_DIR="$HOME/Downloads"
-REPO_PATH="$DOWNLOADS_DIR/dotfiles"
-DOTFILES_PATH="$REPO_PATH/dotfiles"
-DROPBOX_VERSION="dropbox_2015.10.28_amd64.deb"
-ADOBE_PACKAGE="AdbeRdr9.5.5-1_i386linux_enu.deb"
-declare -a NODE_VERSION=(
-                        'v5.1.0',
-                        'node-v5.1.0-linux-x64'
-                        )
-
-#----------------------------------------------------------------------
-#  HELPER FUNCTIONS
-#----------------------------------------------------------------------
-# ---- COLORS ----
-# Example usage format:
-# printf "$COLOR" "text"
-light_blue='\e[1;94m%s\e[0m\n'
-light_red='\e[1;91m%s\e[0m\n'
-light_green='\e[1;92m%s\e[0m\n'
-light_cyan='\e[1;96m%s\e[0m\n'
-light_yellow='\e[1;93m%s\e[0m\n'
-dark_gray='\e[1;100m%s\e[0m\n'
-
-# -- endcolors --
+source vars
 
 breakline ()
 {
@@ -66,11 +41,6 @@ installAnsible ()
 {
   breakline "Installing Ansible"
 
-  which ansible > /dev/null 2>&1
-  if [[ "$?" -eq 0 ]]; then
-    printf "$light_red" "[ERROR] Ansible already installed. Exiting..."
-    exit 1
-  fi
   sudo apt-add-repository ppa:ansible/ansible --yes
   sudo apt-get update && sudo apt-get install -y ansible
 }
@@ -79,11 +49,6 @@ installChrome ()
 {
   breakline "Installing Google Chrome"
 
-  apt-cache show google-chrome-stable > /dev/null 2>&1
-  if [[ "$?" -eq 0 ]]; then
-    printf "$light_red" "[ERROR] Chrome already installed. Exiting..."
-    exit 1
-  fi
   # Install dependencies
   sudo apt-get -y install \
     libxss1 \
@@ -106,11 +71,6 @@ installDocker ()
 
   breakline "Installing Docker"
     
-  which docker > /dev/null 2>&1
-  if [[ "$?" -eq 0 ]]; then
-    printf "$light_red" "[ERROR] Docker already installed. Exiting..."
-    exit 1
-  fi
   Install  docker
   curl -sSL https://get.docker.com/ | sh
   sudo usermod -aG docker $USER
@@ -126,10 +86,6 @@ installDotfiles ()
 {
   breakline "Copying and configuring dotfiles"
 
-  if [[ -e "$HOME/.vimrc" && -e "$HOME/.bashrc" && -e "$HOME/.tmux.conf" ]]; then
-    printf "$light_red" "[ERROR] Dotfiles have already been copied. Exiting..."
-    exit 1
-  fi
   git clone https://github.com/dminca/dotfiles.git $DOWNLOADS_DIR/dotfiles
 
   cp -fv $DOTFILES_PATH/.taskrc \
@@ -143,11 +99,6 @@ installDropbox ()
 {
   breakline "Installing Dropbox"
 
-  apt-cache show dropbox > /dev/null 2>&1
-  if [[ "$?" -eq 0 ]]; then
-    printf "$light_red" "[ERROR] Dropbox already installed. Exiting..."
-    exit 1
-  fi
   wget -P $DOWNLOADS_DIR https://linux.dropbox.com/packages/ubuntu/$DROPBOX_VERSION
 
   sudo dpkg -i $DOWNLOADS_DIR/$DROPBOX_VERSION
@@ -157,10 +108,6 @@ installFont ()
 {
   breakline "Pulling the Hack font"
 
-  if [[ -e "$HOME/.fonts/truetype/Hack-Regular.ttf" ]]; then
-    printf "$light_red" "[ERROR] Hack font already installed. Exiting..."
-    exit 1
-  fi
   mkdir -p $HOME/.fonts/truetype
   wget -P $HOME/.fonts/truetype https://github.com/chrissimpkins/Hack/releases/download/v2.018/Hack-v2_018-ttf.zip
   unzip $HOME/.fonts/truetype/Hack-v2_018-ttf.zip -d $HOME/.fonts/truetype/
@@ -173,11 +120,6 @@ installNode ()
 {
   breakline "Installing Node (latest)"
 
-  node --version > /dev/null 2>&1
-  if [[ "$?" -eq 0 ]]; then
-    printf "$light_red" "[ERROR] NodeJS already installed. Exiting..."
-    exit 1
-  fi
   wget -P $DOWNLOADS_DIR https://nodejs.org/dist/${NODE_VERSION[0]}/${NODE_VERSION[1]}.tar.gz
 
   tar xvf $DOWNLOADS_DIR/${NODE_VERSION[1]}.tar.gz -C $DOWNLOADS_DIR
@@ -232,11 +174,6 @@ installSublime ()
 {
   breakline "Installing Sublime Text 3 build 3065"
 
-  subl --version > /dev/null 2>&1
-  if [[ "$?" -eq 0 ]]; then
-    printf "$light_red" "[ERROR] Sublime already installed. Exiting..."
-    exit 1
-  fi
   wget -P $DOWNLOADS_DIR http://c758482.r82.cf2.rackcdn.com/sublime-text_build-3065_amd64.deb
 
   sudo dpkg -i $DOWNLOADS_DIR/sublime-text_build-3065_amd64.deb
@@ -252,11 +189,6 @@ installTask ()
 {
   breakline "Installing tasksh by taskwarrior"
 
-  which tasksh > /dev/null 2>&1
-  if [[ "$?" -eq 0 ]]; then
-    printf "$light_red" "[ERROR] TaskSH has already been installed. Exiting..."
-    exit 1
-  fi
   wget http://taskwarrior.org/download/tasksh-latest.tar.gz --directory-prefix=$DOWNLOADS_DIR
 
   cd $DOWNLOADS_DIR
@@ -284,10 +216,6 @@ installVim ()
 {
   breakline "Configuring vim & pulling plugins"
 
-  if [[ -d "$VIM_PATH" ]]; then
-    printf "$light_red" "[ERROR] Vim has already been configured"
-    exit 1
-  fi
   mkdir -p $VIM_PATH/autoload \
            $VIM_PATH/bundle \
            $VIM_PATH/snippets \
@@ -324,12 +252,6 @@ installWireshark ()
 {
   breakline "Installing Wireshark"
 
-  which wireshark > /dev/null 2>&1
-  if [[ "$?" -eq 0 ]]; then
-    printf "$light_red" "[ERROR] Wireshark already installed. Exiting..."
-    exit 1
-  fi
-  printf "$light_green" "[OK] Installing..."
   sudo apt-get install -y wireshark
   sudo groupadd wireshark
   sudo usermod -a -G wireshark $USER
@@ -343,11 +265,6 @@ installZsh ()
 {
   breakline "Installing Zshell (zsh)"
 
-  which zsh > /dev/null 2>&1
-  if [[ "$?" -eq 0 ]]; then
-    printf "$light_red" "[ERROR] ZSH already installed. Exiting..."
-    exit 1
-  fi
   curl -L http://install.ohmyz.sh > $HOME/Downloads/install.sh
 
   sh $HOME/Downloads/install.sh
@@ -359,11 +276,6 @@ installZsh ()
 #-------------------------------------------------------------------------
 cleanup_memory ()
 {
-  dpkg -l 'linux-*' > /dev/null 2>&1
-  if [[ $? -ne 0 ]]; then
-    printf "$light_red" "No linux headers...exiting"
-    exit 1
-  fi
   dpkg -l 'linux-*' |\
   sed '/^ii/!d;/'"$(uname -r |\
   sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' |\
@@ -385,11 +297,6 @@ themePaper ()
 {
   breakline "Installing Paper theme and Icon pack"
 
-  apt-cache show paper-gtk-theme > /dev/null 2>&1
-  if [[ "$?" -eq 0 ]]; then
-    printf "$light_red" "[ERROR] Paper theme already installed. Exiting..."
-    exit 1
-  fi
   sudo add-apt-repository -y ppa:snwh/pulp
 
   sudo apt-get update
@@ -401,11 +308,6 @@ themeNumix ()
 {
   breakline "Installing Numix themne and Icon pack"
 
-  apt-cache show numix-icon-theme > /dev/null 2>&1
-  if [[ "$?" -eq 0 ]]; then
-    printf "$light_red" "[ERROR] Numix theme already installed. Exiting..."
-    exit 1
-  fi
   sudo apt-add-repository -y ppa:numix/ppa
 
   sudo apt-get update
@@ -417,77 +319,149 @@ selectiveInstall ()
 {
   whiptail --title "Package chooser" --checklist --separate-output \
     "What packages do you wish to install?" 20 78 15 \
-    "bins" "Install binaries" off \
-    "docker" "Install Docker tools" off \
-    "ansible" "Install Ansible for DevOps" off \
-    "vim" "Pull vim plugins and .vimrc" off \
-    "tasker" "Install tasksh by TaskWarrior" off \
-    "dotfiles" "Pull the dotfiles and set them up" off \
-    "chrome" "Just install the Chrome browser" off \
-    "font" "Install the Hack font for terminal" off \
-    "dropbox" "Install Dropbox file sync" off \
     "adobeReader" "Install Adobe Reader" off \
+    "ansible" "Install Ansible for DevOps" off \
+    "chrome" "Just install the Chrome browser" off \
+    "docker" "Install Docker tools" off \
+    "dotfiles" "Pull the dotfiles and set them up" off \
+    "dropbox" "Install Dropbox file sync" off \
+    "font" "Install the Hack font for terminal" off \
+    "bins" "Install binaries" off \
+    "numix" "Material Design icon theme for Unix" off \
+    "paper" "Paper Material Design theme for Unix" off \
     "sublime" "Install Sublime Text 3 Full" off \
+    "tasker" "Install tasksh by TaskWarrior" off \
+    "cleanupMem" "Issue a cleanup memory operation" off \
+    "vim" "Pull vim plugins and .vimrc" off \
     "installWireshark" "Install Wireshark packet analyser" off \
     "nodeJS" "Fetch & install NodeJS" off \
-    "zsh" "Another Bash for your terminal" off \
-    "numix" "Material Design icon theme for Unix" off \
-    "cleanupMem" "Issue a cleanup memory operation" off \
-    "paper" "Paper Material Design theme for Unix" off 2>results
+    "zsh" "Another Bash for your terminal" off 2>results
 
   while read choice
   do
     case $choice in
-      bins)
-        installPkgs
-        ;;
-      docker)
-        installDocker
-        ;;
-      ansible)
-        installAnsible
-        ;;
-      vim)
-        installVim
-        ;;
-      tasker)
-        installTask
-        ;;
-      dotfiles)
-        installDotfiles
-        ;;
-      chrome)
-        installChrome
-        ;;
-      font)
-        installFont
-        ;;
-      dropbox)
-        installDropbox
-        ;;
       adobeReader)
         installAdobe
         ;;
+      ansible)
+        which gedit > /dev/null 2>&1
+        if [[ "$?" -eq 0 ]]; then
+          printf "$light_red" "[ERROR] Ansible already installed. Exiting..."
+          exit 1
+        fi
+        installAnsible
+        ;;
+      chrome)
+        apt-cache show google-chrome-stable > /dev/null 2>&1
+        if [[ "$?" -eq 0 ]]; then
+          printf "$light_red" "[ERROR] Chrome already installed. Exiting..."
+          exit 1
+        fi
+        installChrome
+        ;;
+      docker)
+        which docker > /dev/null 2>&1
+        if [[ "$?" -eq 0 ]]; then
+          printf "$light_red" "[ERROR] Docker already installed. Exiting..."
+          exit 1
+        fi
+        installDocker
+        ;;
+      dotfiles)
+        if [[ -e "$HOME/.vimrc" && -e "$HOME/.bashrc" && -e "$HOME/.tmux.conf" ]]; then
+          printf "$light_red" "[ERROR] Dotfiles have already been copied. Exiting..."
+          exit 1
+        fi
+        installDotfiles
+        ;;
+      dropbox)
+        apt-cache show dropbox > /dev/null 2>&1
+        if [[ "$?" -eq 0 ]]; then
+          printf "$light_red" "[ERROR] Dropbox already installed. Exiting..."
+          exit 1
+        fi
+        installDropbox
+        ;;
+      font)
+        if [[ -e "$HOME/.fonts/truetype/Hack-Regular.ttf" ]]; then
+          printf "$light_red" "[ERROR] Hack font already installed. Exiting..."
+          exit 1
+        fi
+        installFont
+        ;;
+      bins)
+        installPkgs
+        ;;
+      numix)
+        apt-cache show numix-icon-theme > /dev/null 2>&1
+        if [[ "$?" -eq 0 ]]; then
+          printf "$light_red" "[ERROR] Numix theme already installed. Exiting..."
+          exit 1
+        fi
+        themeNumix
+        ;;
+      paper)
+        apt-cache show paper-gtk-theme > /dev/null 2>&1
+        if [[ "$?" -eq 0 ]]; then
+          printf "$light_red" "[ERROR] Paper theme already installed. Exiting..."
+          exit 1
+        fi
+        themePaper
+        ;;
       sublime)
+        subl --version > /dev/null 2>&1
+        if [[ "$?" -eq 0 ]]; then
+          printf "$light_red" "[ERROR] Sublime already installed. Exiting..."
+          exit 1
+        fi
         installSublime
         ;;
+      tasker)
+        which tasksh > /dev/null 2>&1
+        if [[ "$?" -eq 0 ]]; then
+          printf "$light_red" "[ERROR] TaskSH has already been installed. Exiting..."
+          exit 1
+        fi
+        installTask
+        ;;
+      cleanupMem)
+        dpkg -l 'linux-*' > /dev/null 2>&1
+        if [[ $? -ne 0 ]]; then
+          printf "$light_red" "No linux headers...exiting"
+          exit 1
+        fi
+        cleanup_memory
+        ;;
+      vim)
+        if [[ -d "$VIM_PATH" ]]; then
+          printf "$light_red" "[ERROR] Vim has already been configured"
+          exit 1
+        fi
+        installVim
+        ;;
       installWireshark)
+        which wireshark > /dev/null 2>&1
+        if [[ "$?" -eq 0 ]]; then
+          printf "$light_red" "[ERROR] Wireshark already installed. Exiting..."
+          exit 1
+        fi
         installWireshark
         ;;
       nodeJS)
+        node --version > /dev/null 2>&1
+        if [[ "$?" -eq 0 ]]; then
+          printf "$light_red" "[ERROR] NodeJS already installed. Exiting..."
+          exit 1
+        fi
         installNode
         ;;
       zsh)
+        which zsh > /dev/null 2>&1
+        if [[ "$?" -eq 0 ]]; then
+          printf "$light_red" "[ERROR] ZSH already installed. Exiting..."
+          exit 1
+        fi
         installZsh
-        ;;
-      numix)
-        themeNumix
-        ;;
-      cleanupMem)
-        cleanup_memory
-        ;;
-      paper)
-        themePaper
         ;;
       *)
         echo "Nothing selected, exiting.."
